name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install nats-server
        uses: aricart/install-binary@v1.0.0
        with:
          repo: nats-io/nats-server
          name: nats-server
          cache: true
      
      - run: nats-server -js &
      
      - run: yarn compile
      - run: yarn test:coverage

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: ./coverage/lcov.info
          os: linux
          token: ${{ secrets.CODECOV_TOKEN }}
